<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hanny Aqilah">
<meta name="dcterms.date" content="2024-01-05">

<title>Pengaruh Inflasi Terhadap Jumlah Nilai Ekspor di Indonesia Tahun 2000 Hingga 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Inflasi Terhadap Jumlah Nilai Ekspor di Indonesia Tahun 2000 Hingga 2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hanny Aqilah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 5, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">logo poltek app</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia adalah salah satu negara berkembang yang memiliki potensi ekspor yang besar. Ekspor merupakan salah satu sumber devisa dan pendapatan nasional yang penting bagi perekonomian Indonesia. Menurut data Satu Data Perdagangan, nilai ekspor Indonesia pada tahun 2023 mencapai 1.824,9 triliun rupiah, meningkat 15,4% dibandingkan tahun 2022. Ekspor Indonesia terdiri dari berbagai komoditas, seperti minyak dan gas, pertanian, perkebunan, industri, dan pertambangan.</p>
<p>Namun, kinerja ekspor Indonesia juga dipengaruhi oleh berbagai faktor, baik dari dalam maupun luar negeri. Salah satu faktor yang berpengaruh adalah inflasi. Inflasi adalah kenaikan harga-harga secara umum dan terus menerus yang menyebabkan menurunnya daya beli masyarakat. Inflasi dapat mempengaruhi nilai tukar mata uang, biaya produksi, serta permintaan produk ekspor. Di sisi lain, ekspor dapat mempengaruhi perekonomian nasional dan nilai tukar mata uang.</p>
<p>Hubungan antara inflasi dan ekspor adalah hubungan yang kompleks dan saling mempengaruhi. Beberapa penelitian sebelumnya telah mengkaji hubungan ini dengan menggunakan berbagai metode dan variabel. Namun, hasil penelitian tersebut masih bervariasi dan belum ada kesepakatan yang pasti. Oleh karena itu, penelitian ini bertujuan untuk menganalisis pengaruh inflasi terhadap jumlah nilai ekspor di Indonesia tahun 2000-2022 dengan menggunakan data sekunder dari World Bank dan Uncomtrade. Penelitian ini diharapkan dapat memberikan kontribusi bagi pengembangan ilmu ekonomi, khususnya mengenai hubungan inflasi dan ekspor, serta memberikan masukan bagi pemerintah dalam merumuskan kebijakan ekonomi yang tepat.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Terdapat dua variabel ( variabel X, variabel Y) yang digunakan sebagai objek penelitian ini. Peneliti pengambil data objek variabel X melalui data.worldbank.org berupa inflasi Indonesia. Sedangkan variabel Y peneliti mengambil data objek dari uncomtrade berupa jumlah ekspor Indonesia. Data bersifat time series dalam kurun waktu tahun 2000 hingga 2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="a">
<li><p>Apakahh inflasi mempengaruhi ekspor di Indonesia?</p></li>
<li><p>Bagaimana hubungan inflasi terhadap ekspor di Indonesia ?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian pengaruh inflasi terhadap ekspor di Indonesia untuk mengetahui arah dan besarnya pengaruh inflasi terhadap ekspor di Indonesia.</p>
<p>Manfaat dari penelitian ini dapat dibagi menjadi manfaat akademis dan manfaat praktis.</p>
<p><strong>Manfaat akademis</strong></p>
<p>Untuk menambah pengetahuan dan wawasan tentang pengaruh inflasi terhadap ekspor di Indonesia. Penelitian ini juga dapat digunakan sebagai referensi penelitian lain yang ingin melakukan penelitian serupa.</p>
<p><strong>Manfaat praktis</strong></p>
<p>Untuk memberikan informasi kepada pemerintah dan pelaku usaha tentang pengaruh inflasi terhhadap ekspor di Indonesia. Informasi ini dapat digunakan oleh pemerintah untuk Menyusun kebijakan yang tepat untuk mengendalikan inflasi dan meningkatkan ekspor.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Package yang digunakan dalam penelitian ini antara lain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>INFLASI</strong></p>
<p>Inflasi adalah kondisi di mana harga-harga kebanyakan barang dan jasa mengalami peningkatan secara terus-menerus dalam periode tertentu. Misalnya, harga beras, minyak goreng, dan bensin naik setiap bulannya. Jika hanya ada satu atau dua macam barang yang harganya naik, hal itu belum bisa dikatakan sebagai inflasi, kecuali jika kenaikan tersebut menyebar atau memicu kenaikan harga barang lainnya. Misalnya, kenaikan harga bensin dapat menyebabkan kenaikan harga transportasi, makanan, dan barang-barang lain yang membutuhkan bensin sebagai bahan bakar. Keadaan yang bertolak belakang dengan inflasi adalah deflasi. Deflasi adalah kondisi di mana harga-harga barang dan jasa mengalami penurunan secara umum dan terus menerus dalam periode tertentu. Deflasi dapat terjadi karena adanya penurunan permintaan, peningkatan produksi, atau penurunan jumlah uang beredar. Untuk menghitung dan mengumpulkan data inflasi, Badan Pusat Statistik (BPS) melakukan survei dengan mengambil sampel harga barang yang mencerminkan pola konsumsi masyarakat pada umumnya. Sampel harga barang tersebut disebut sebagai indeks harga konsumen (IHK). IHK adalah ukuran yang menggambarkan perubahan harga sekelompok barang dan jasa yang dikonsumsi oleh rumah tangga. Ada beberapa faktor yang dapat menyebabkan inflasi, antara lain adalah adanya tekanan dari penawaran (cost push inflation), adanya tekanan dari permintaan (demand pull inflation), dan adanya ekspektasi inflasi. Tekanan dari penawaran adalah faktor yang menyebabkan inflasi karena adanya kenaikan biaya produksi, misalnya karena kenaikan harga bahan baku, upah, pajak, atau subsidi. Tekanan dari permintaan adalah faktor yang menyebabkan inflasi karena adanya kenaikan permintaan barang dan jasa yang melebihi kapasitas produksi, misalnya karena adanya pertumbuhan penduduk, pendapatan, atau pengeluaran pemerintah. Ekspektasi inflasi adalah faktor yang menyebabkan inflasi karena adanya keyakinan atau prediksi bahwa harga-harga akan terus naik di masa depan, sehingga mendorong masyarakat untuk menaikkan harga, upah, atau permintaan barang dan jasa saat ini.</p>
<p><strong>EKSPOR</strong></p>
<p>Ekspor merupakan aktivitas pengiriman barang atau jasa dari satu negara ke negara lain dalam rangka berdagang. Ekspor umumnya dilakukan oleh perusahaan yang memiliki surplus produksi atau berkeinginan untuk memasuki pasar internasional. Ekspor juga dapat memperbesar pendapatan dan pertumbuhan ekonomi suatu negara, serta menambah lapangan kerja dan devisa Ekspor terbagi menjadi dua macam, yaitu ekspor langsung dan ekspor tidak langsung. Ekspor langsung adalah saat penjual atau eksportir menjual barang atau jasa secara langsung ke pembeli atau importir di negara lain. Ekspor tidak langsung adalah saat penjual atau eksportir menjual barang atau jasa dengan menggunakan perantara, seperti perusahaan manajemen ekspor atau perusahaan pengekspor, yang lalu menjualnya ke negara lain Untuk melakukan ekspor, ada beberapa langkah yang harus dilakukan, seperti mendaftarkan diri sebagai eksportir, mengurus izin, menyiapkan dokumen, membayar pajak, dan mengirimkan barang. Langkah ini dapat beragam tergantung pada jenis barang, negara tujuan, dan peraturan yang berlaku.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>INFLASI(x)</th>
<th>LOGEKSPOR(y)</th>
<th>EKSPOR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>20,4</td>
<td>10,79</td>
<td>$62.124.006.936,00</td>
</tr>
<tr class="even">
<td>14,3</td>
<td>10,75</td>
<td>$56.316.866.700,00</td>
</tr>
<tr class="odd">
<td>5,9</td>
<td>10,76</td>
<td>$57.158.751.145,00</td>
</tr>
<tr class="even">
<td>5,5</td>
<td>10,79</td>
<td>$61.058.187.386,00</td>
</tr>
<tr class="odd">
<td>8,6</td>
<td>10,85</td>
<td>$71.582.468.122,00</td>
</tr>
<tr class="even">
<td>14,3</td>
<td>10,93</td>
<td>$85.659.947.504,00</td>
</tr>
<tr class="odd">
<td>14,1</td>
<td>11,00</td>
<td>$100.798.615.667,00</td>
</tr>
<tr class="even">
<td>11,3</td>
<td>11,06</td>
<td>$114.100.872.803,00</td>
</tr>
<tr class="odd">
<td>18,1</td>
<td>11,14</td>
<td>$137.020.424.402,00</td>
</tr>
<tr class="even">
<td>8,3</td>
<td>11,07</td>
<td>$116.509.991.781,00</td>
</tr>
<tr class="odd">
<td>15,3</td>
<td>11,20</td>
<td>$157.779.103.470,00</td>
</tr>
<tr class="even">
<td>7,5</td>
<td>11,31</td>
<td>$203.496.619.185,00</td>
</tr>
<tr class="odd">
<td>3,8</td>
<td>11,28</td>
<td>$190.031.839.234,00</td>
</tr>
<tr class="even">
<td>5</td>
<td>11,26</td>
<td>$182.551.754.383,00</td>
</tr>
<tr class="odd">
<td>5,4</td>
<td>11,25</td>
<td>$176.036.194.332,00</td>
</tr>
<tr class="even">
<td>4</td>
<td>11,18</td>
<td>$150.366.281.305,00</td>
</tr>
<tr class="odd">
<td>2,4</td>
<td>11,16</td>
<td>$144.489.796.418,00</td>
</tr>
<tr class="even">
<td>4,3</td>
<td>11,23</td>
<td>$168.827.554.042,00</td>
</tr>
<tr class="odd">
<td>3,8</td>
<td>11,26</td>
<td>$180.215.034.094,00</td>
</tr>
<tr class="even">
<td>1,6</td>
<td>11,22</td>
<td>$167.682.995.133,00</td>
</tr>
<tr class="odd">
<td>-0,4</td>
<td>11,21</td>
<td>$163.191.837.310,00</td>
</tr>
<tr class="even">
<td>6</td>
<td>11,36</td>
<td>$231.522.458.128,00</td>
</tr>
<tr class="odd">
<td>9,6</td>
<td>11,47</td>
<td>$291.979.090.608,00</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data time series pada kurun waktu 2000 hingga 2022. Pada variabel Y data berbentuk USD, yang kemudian peneliti melakukan log terhadap variabel “EKSPOR” untuk mendapatkan satuan yang sama, sehingga menghasilkan data seperti pada “LOGEKSPOR”,yang nantinya akan dijadikan objek penelitian sebagai variabel Y.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>datahanny<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/METODOLOGI/hanny/datahanny.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datahanny)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
      x  logy           y
  &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;
1  20.4  10.8 62124006936
2  14.3  10.8 56316866700
3   5.9  10.8 57158751145
4   5.5  10.8 61058187386
5   8.6  10.9 71582468122
6  14.3  10.9 85659947504</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>datahanny,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>logy))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"pink"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan inflasi dan ekspor"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"inflasi"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Jumlah nilai ekspor"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: data.worldbank.org,uncomtrade"</span>)<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat dengan “logy” sebagai variabel dependen. Penelitian ini dimaksud untuk mencari hubungan antara inflasi terhadap ekspor, dengan spesifikasi yang dilakukan sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah ekspor dan <span class="math inline">\(x_t\)</span> adalah inflasi.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>variable</th>
<th>coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>11.237928</td>
</tr>
<tr class="even">
<td>X</td>
<td>-0.015623</td>
</tr>
<tr class="odd">
<td>Multiple R-squared</td>
<td>0.1746</td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0.1353</td>
</tr>
<tr class="odd">
<td>F-statistic</td>
<td>4.443</td>
</tr>
<tr class="even">
<td>p-value</td>
<td>0.04723</td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang telah didapatkan dimasukkan ke dalam rumus , sehingga menjadi: <span class="math display">\[
y_{t}=\ 11.237928 - \ 0.015623x+\mu_t
\]</span></p>
<p>Dari hasil tersebut dapat dilihat bahwa inflasi berpengaruh negatif terhadap jumlah nilai ekspor di Indonesia, yang artinya apabila inflasi naik satu, maka ekspor akan mengalami penurunan sebesar 0.015623.</p>
<p>Pengaruh inflasi yang negarif terhadap ekspor dapat terjadi apabila inflasi terjadi di Indonesia. Hal ini dapat menyebabkan peningkatan biaya produksi barang ekspor yang disebabkan karena kenaikan harga bahan baku, tenaga kerja, dan biaya oprasional lainnya.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/METODOLOGI/hanny"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>datahanny <span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"datahanny.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(logy<span class="sc">~</span>x,<span class="at">data =</span> datahanny)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logy ~ x, data = datahanny)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.38867 -0.06181  0.00172  0.10092  0.37741 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 11.237928   0.073010 153.922   &lt;2e-16 ***
x           -0.015623   0.007412  -2.108   0.0472 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1928 on 21 degrees of freedom
Multiple R-squared:  0.1746,    Adjusted R-squared:  0.1353 
F-statistic: 4.443 on 1 and 21 DF,  p-value: 0.04723</code></pre>
</div>
</div>
<p>Nilai multiple R-squared sebesar 0.1746, dan F-statistic 4.443, nilai multiple R-squared ini menunjukkan bahwa model regresi hanya dapat menjelaskan 17.46% variasi y, sedangkan sisanya dipengaruhi oleh faktor lain.</p>
<p>Nilai F-statistik memiliki p-value sebesar 0.04723, yang berarti model regresi signifikan pada tingkat signifikansi 5%. Secara keseluruhan, analisis regresi menunjukkan bahwa ada hubungan negatif dan signifikan antara x dan y, tetapi model regresi memiliki kualitas yang rendah dalam menjelaskan variasi y. Maka peneliti perlu menambahkan variabel lain untuk meningkatkan kualitas model regresi.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Kenaikan biaya produksi dapat menyebabkan harga barang ekspor menjadi lebih mahal. Hal ini mengurangi daya saing barang ekspor dari Indonesia di pasar international. Selain itu inflasi Indonesia juga dapat menyebabkan nilai tukar melemah terhadap mata uang negara tujuan ekspor.</p>
<p>Inflasi berpengaruh signifikan terhadap jumlah nilai ekspor di Indonesia dalam kurun waktu periode tahun 2000 hingga 2022. Hal ini ditunjukkan dengan nilai coefficients pada x -0.015623 yang artinya setiap kenaikan satu pada inflasi dapat menurunkan jumlah nilai ekspor sebesar 0.015623. Dapat disimpulkan bahwa inflasi berpengaruh namun negatif terhadap jumlahh nilai ekspor. Namun perlu dicatat bahwa peneliti perlu menambah faktor-faktor yang dapat mempengaruhi ekspor, seperti nilai tukar dan sebagainya, untuk mendapatkan kualitas model yang lebih baik dalam menjelaskan variasi y.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Elva Dona, Habibatul Hidayati, Khairil Aswan, Rusdandi Oktavian, &amp; Irwan Muslim.(2022). Berpengaruhkah Jumlah Uang Beredar, Suku Bunga, Ekspor dan Impor terhadap Inflasi di Indonesia? Jurnal Ekobistek, 355–360. https://doi.org/10.35134/ekobistek.v11i4.411</p>
<p>Ginting, A. M. (2017). ANALISIS PENGARUH EKSPOR TERHADAP PERTUMBUHAN EKONOMI INDONESIA. Buletin Ilmiah Litbang Perdagangan, 11(1), 1–20. https://doi.org/10.30908/bilp.v11i1.185</p>
<p>Mutia, R. (t.t.). FAKULTAS EKONOMIKA DAN BISNIS UNIVERSITAS DIPONEGORO SEMARANG 2015.</p>
<p>Silaban, R. (2022). PENGARUH NILAI TUKAR DAN INFLASI TERHADAP EKSPOR NON MIGAS DI INDONESIA. 6(1).</p>
<p>Widyasanti, A. A. (2010). PERDAGANGAN BEBAS REGIONAL DAN DAYA SAING EKSPOR: KASUS INDONESIA. Buletin Ekonomi Moneter dan Perbankan, 13(1), 5–22. https://doi.org/10.21098/bemp.v13i1.251</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>